// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        (unknown)
// source: tests/middleware/tracing/v1/hello.proto

package tracingpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HelloRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_tests_middleware_tracing_v1_hello_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tests_middleware_tracing_v1_hello_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_tests_middleware_tracing_v1_hello_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_tests_middleware_tracing_v1_hello_proto protoreflect.FileDescriptor

var file_tests_middleware_tracing_v1_hello_proto_rawDesc = []byte{
	0x0a, 0x27, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2f, 0x6d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x77, 0x61,
	0x72, 0x65, 0x2f, 0x74, 0x72, 0x61, 0x63, 0x69, 0x6e, 0x67, 0x2f, 0x76, 0x31, 0x2f, 0x68, 0x65,
	0x6c, 0x6c, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1b, 0x74, 0x65, 0x73, 0x74, 0x73,
	0x2e, 0x6d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x77, 0x61, 0x72, 0x65, 0x2e, 0x74, 0x72, 0x61, 0x63,
	0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31, 0x22, 0x22, 0x0a, 0x0c, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x27, 0x5a, 0x25, 0x74, 0x65,
	0x73, 0x74, 0x73, 0x2f, 0x6d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x77, 0x61, 0x72, 0x65, 0x2f, 0x74,
	0x72, 0x61, 0x63, 0x69, 0x6e, 0x67, 0x2f, 0x76, 0x31, 0x3b, 0x74, 0x72, 0x61, 0x63, 0x69, 0x6e,
	0x67, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tests_middleware_tracing_v1_hello_proto_rawDescOnce sync.Once
	file_tests_middleware_tracing_v1_hello_proto_rawDescData = file_tests_middleware_tracing_v1_hello_proto_rawDesc
)

func file_tests_middleware_tracing_v1_hello_proto_rawDescGZIP() []byte {
	file_tests_middleware_tracing_v1_hello_proto_rawDescOnce.Do(func() {
		file_tests_middleware_tracing_v1_hello_proto_rawDescData = protoimpl.X.CompressGZIP(file_tests_middleware_tracing_v1_hello_proto_rawDescData)
	})
	return file_tests_middleware_tracing_v1_hello_proto_rawDescData
}

var file_tests_middleware_tracing_v1_hello_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tests_middleware_tracing_v1_hello_proto_goTypes = []any{
	(*HelloRequest)(nil), // 0: tests.middleware.tracing.v1.HelloRequest
}
var file_tests_middleware_tracing_v1_hello_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tests_middleware_tracing_v1_hello_proto_init() }
func file_tests_middleware_tracing_v1_hello_proto_init() {
	if File_tests_middleware_tracing_v1_hello_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tests_middleware_tracing_v1_hello_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tests_middleware_tracing_v1_hello_proto_goTypes,
		DependencyIndexes: file_tests_middleware_tracing_v1_hello_proto_depIdxs,
		MessageInfos:      file_tests_middleware_tracing_v1_hello_proto_msgTypes,
	}.Build()
	File_tests_middleware_tracing_v1_hello_proto = out.File
	file_tests_middleware_tracing_v1_hello_proto_rawDesc = nil
	file_tests_middleware_tracing_v1_hello_proto_goTypes = nil
	file_tests_middleware_tracing_v1_hello_proto_depIdxs = nil
}
